# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/PredictiveMaintenance',
                'doc_host': 'https://lalithapavani-b.github.io',
                'git_url': 'https://github.com/lalithapavani-b/PredictiveMaintenance',
                'lib_path': 'PredictiveMaintenance'},
  'syms': {'PredictiveMaintenance.core': {'PredictiveMaintenance.core.foo': ('core.html#foo', 'PredictiveMaintenance/core.py')}}}
